# Generated by Django 5.1.6 on 2025-02-16 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagemetrics',
            options={'managed': False},
        ),
    ]
