# Generated by Django 5.1.6 on 2025-02-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usagemetrics_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usagemetrics',
            table='UsageMetrics',
        ),
    ]
