# Generated by Django 5.1.6 on 2025-02-17 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usagemetrics_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
