# Generated by Django 5.1.6 on 2025-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'For the first 200 kWh (1 - 200 kWh) per month'), (2, 'For the next 100 kWh (201 - 300 kWh) per month'), (3, 'For the next 300 kWh (301 - 600 kWh) per month'), (4, 'For the next 300 kWh (601 - 900 kWh) per month'), (5, 'For the next kWh (901 kWh onwards) per month')], unique=True)),
                ('unit', models.CharField(default='sen/kWh', max_length=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
